### ISSUE TITLE
Merge Installation page with Quick Start page?

### ISSUE THREAD

**Issue by Hanawa02** [snowpackjs/astro-docs#33]
There is a lot of overlapping content from both pages, I believe we could merge them both in a way that we can have the "quick start" followed by the rest of the "installation" content.

I believe this should be done after these two PR's are completed so that no content is missed or we have double work.
- https://github.com/snowpackjs/astro-docs/pull/32
- https://github.com/snowpackjs/astro-docs/pull/16

**Comment by Hanawa02** [comment]
@FredKSchott @itskitto @aFuzzyBear @jgil-r

**Comment by jgil-r** [comment]
The only difference is that the installation page briefly mentions node.js as a dependency. I can just add that to the top of quick-start page and completely get rid of installation page. Currently we have very similar information in `/`, `/installation`, and `/quick-start` pages. I mentioned in #32 that we can avoid repetitive information by making the sidebar headings just be headings or links that route to the first link of that specific group. For example, instead of Basic Concepts having its own page, it should just link to Project Structure.

**Comment by Hanawa02** [comment]
@jgil-r I agree with the sidebar, but for the installation page, I believe it would be better to check PR #16, since @aFuzzyBear changed a lot of the page content.

**Comment by itskitto** [comment]
Yeah, I'm not sure if we need a distinction between Installation and Quick Start, they seem to be one in the same. I think we can merge them in a way that's concise and to the point and then break out @aFuzzyBear's extended information into a "Deep Dives" section and link it in the Quick Start/Installation merge

**Comment by aFuzzyBear** [comment]
Hey guys thats me made the changes to the install and in the index page, If we can merge them, idk what the best way for that would be, whatever you guys think is best, Once they are merged there is a few link adding that I need to do just to link them to other doc pages for reference, 
thanks for your support team =)

**Comment by FredKSchott** [comment]
Docs improved in https://github.com/snowpackjs/astro-docs/commit/d2027d928ee04d2af38bab39878c38f0681f422c to make this separation more clear
