### ISSUE TITLE
Pages for Group `Basic Concepts`

### ISSUE THREAD

**Issue by Hanawa02** [snowpackjs/astro-docs#7]
Task  -> Assignee
- [x] Project Structure -> 
- [x] Astro Pages -> 
- [x] Astro Components -> 
- [x] Component Hydration -> @itskitto 
- [x] Layouts -> @ewatch
- [x] Styling -> @itskitto 
- [x] Content (Markdown) -> @jgil-r
- [x] Data Fetching -> 
- [x] Pagination -> 
- [x] Collections -> 
- [x] Build & Deploy -> 
- [x] URL Sanitization -> Tackled in "Security FAQs" of Markdown document

**Comment by ewatch** [comment]
Layouts -> ewatch

**Comment by itskitto** [comment]
I'll take the styling portion! I want to read more about it so it'll force me to sit down and digest the information on it 😁

**Comment by jgil-r** [comment]
Could I get assigned to Content (Markdown)?

**Comment by itskitto** [comment]
> Could I get assigned to Content (Markdown)?

Gotcha! Are you in the Discord btw? If so what's your username?

**Comment by jgil-r** [comment]
> > Could I get assigned to Content (Markdown)?
> 
> Gotcha! Are you in the Discord btw? If so what's your username?

Yes I am, chuy#5231

**Comment by itskitto** [comment]
I'll take `Component Hydration`

**Comment by Hanawa02** [comment]
@itskitto @FredKSchott I added a new page to this section `URL Sanitization`, not sure if the title is ideal or if it should be part of another group, please let me know your thoughts.

This came out of this PR: https://github.com/snowpackjs/astro-docs/pull/19#discussion_r657479290

**Comment by FredKSchott** [comment]
After moving everything over from the Astro repo, we're in pretty good shape! Here's what I think is left to do:
- Layouts
- Pages
- build & deploy

Getting close!!!

**Comment by FredKSchott** [comment]
Done! All pages are now available! 🥳 

Curious to hear what people would like to do next! Two steps that jump to mind are:
- Edits: Give someone's page a read if you didn't write it yourself, and create a PR to help edit their work. Good chance to review that everything is correct as well, in case something has changed.
- Copy these docs into the main astro repo: Now that the docs are complete, we should copy them back into the main `astro` repo so that any changes made in the main repo are easy to port onto here. (This came up on Discord, but once the site is ready we can move the entire thing into the main astro repo, so this is just a temporary copy step until that work is done).
