### ISSUE TITLE
Pages for Group `Integrations`

### ISSUE THREAD

**Issue by Hanawa02** [snowpackjs/astro-docs#9]
Task  -> Assignee
- [ ] Integrations -> 
- [ ] Deploy Astro -> 
- [ ] Data Sources / CMS -> 
- [ ] State Management -> 
- [ ] Styles & CSS Libraries -> 
- [ ] Developer Tools ->

**Comment by FredKSchott** [comment]
Hey yall, to help us cut down on work to get to a v1, I commented this section out from the sidebar for now. We can add it back in once #8 & #7 are complete!

**Comment by jgil-r** [comment]
> Hey yall, to help us cut down on work to get to a v1, I commented this section out from the sidebar for now. We can add it back in once #8 & #7 are complete!

It looks like #7 and #8 are complete. Can we go ahead and add Integration pages? or are we waiting on some content for them?

**Comment by FredKSchott** [comment]
yup, we should be unblocked to add this now. However, if all we have here is a list of different 3rd party libraries/services to integrate with, maybe it's better to add these as example projects instead? I know that Next.js does this and people really seem to like it: https://github.com/vercel/next.js/tree/canary/examples

There have been a couple of templates already started for Headless Wordpress, Netlify, Vercel, etc. that we could point to instead. This would only take up a single page of our docs site, instead of needing an entire section

**Comment by FredKSchott** [comment]
FYI: the docs have been successfully merged back into the main Astro repo: https://github.com/snowpackjs/astro/tree/main/docs

This issue will be migrated over soon, but if anyone can take a look at this issue before then, please remember to create a PR against the main astro repo instead.
